openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
tags: []
paths: {}
components:
  schemas:
    User:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
        name:
          type: string
servers:
  - url: https://example.com/api
    description: production
    variables: {}
